[package]
name = "resume-builder"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = "1.12.0"
rust-ini = "0.18.0"
shellfish = { version = "0.7.0", features = [ "app", "async-std", "async" ] }
