cv = {
    SOI ~ about ~ EOI
}

about      =  { ^"[about]" ~ NEWLINE ~ email ~ NEWLINE ~ phone }
email      =  { ^"email" ~ "=" ~ email_spec }
phone      =  { ^"phone" ~ "=" ~ phone_spec }
phone_spec =  { ("+" ~ NUMBER{1, 2} ~ WHITESPACE? ~ NUMBER*) | NUMBER* }
email_spec =  { localname ~ "@" ~ domain }
localname  =  { (ASCII_ALPHANUMERIC | "." | "+" | "-" | "_")+ }
domain     =  { (ASCII_ALPHANUMERIC | "." | "-")+ }
WHITESPACE = _{ " " }
